CONSUMER_KEY = ENV['MITERU_CONSUMER_KEY']
CONSUMER_SECRET = ENV['MITERU_CONSUMER_SECRET']

SESSION_SECRET = ENV['MITERU_SESSION_SECRET']
SESSION_EXPIRE_AFTER = ENV['MITERU_SESSION_EXPIRE_AFTER'].to_i

BOOKMARKLET = ENV['MITERU_BOOKMARKLET']
